# Generated by Django 5.2.1 on 2025-06-07 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False, verbose_name='세션 아이디')),
                ('session_nm', models.CharField(max_length=100, verbose_name='세션 이름')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자 아이디')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False, verbose_name='메시지 아이디')),
                ('sender', models.CharField(choices=[('user', '사용자'), ('chatbot', '챗봇')], max_length=10, verbose_name='발신자')),
                ('content', models.TextField(verbose_name='내용')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chatbot.chatsession', verbose_name='세션 아이디')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendInterest',
            fields=[
                ('interest_id', models.AutoField(primary_key=True, serialize=False, verbose_name='추천 관심도 아이디')),
                ('interest_status', models.CharField(choices=[('추천', '추천'), ('확인', '확인'), ('신청', '신청')], max_length=10, verbose_name='관심도')),
                ('plcyNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.policy', verbose_name='정책번호')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자 아이디')),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('search_id', models.AutoField(primary_key=True, serialize=False, verbose_name='검색 기록 아이디')),
                ('query', models.TextField(verbose_name='검색 쿼리')),
                ('search_dt', models.DateTimeField(auto_now_add=True, verbose_name='검색 일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자 아이디')),
            ],
        ),
    ]
