# Generated by Django 5.2.1 on 2025-06-19 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatbot', '0001_initial'),
        ('Home', '0003_policies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendinterest',
            name='plcyNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.policies', verbose_name='정책번호'),
        ),
    ]
