# Generated by Django 5.2.1 on 2025-06-20 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chatbot', '0002_alter_recommendinterest_plcyno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendinterest',
            old_name='plcyNo',
            new_name='plcy_no',
        ),
    ]
