# Generated by Django 5.2.1 on 2025-06-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('plcyNo', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='정책번호')),
                ('plcyNm', models.CharField(max_length=200, null=True, verbose_name='정책명')),
                ('plcyExplnCn', models.TextField(null=True, verbose_name='정책설명내용')),
                ('lclsNm', models.CharField(max_length=100, null=True, verbose_name='정책분류명')),
                ('plcySprtCn', models.TextField(null=True, verbose_name='정책지원내용')),
                ('plcyAplyMthdCn', models.TextField(null=True, verbose_name='정책신청방법내용')),
                ('aplyUrlAddr', models.TextField(null=True, verbose_name='신청URL주소')),
                ('sbmsnDcmntCn', models.TextField(null=True, verbose_name='제출서류내용')),
                ('refUrlAddr1', models.TextField(null=True, verbose_name='참고URL주소1')),
                ('refUrlAddr2', models.TextField(null=True, verbose_name='참고URL주소2')),
                ('inqCnt', models.IntegerField(null=True, verbose_name='조회수')),
                ('aplyStartYmd', models.DateField(null=True, verbose_name='신청시작일자')),
                ('aplyEndYmd', models.DateField(null=True, verbose_name='신청종료일자')),
            ],
        ),
    ]
