# Generated by Django 5.2.1 on 2025-06-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatbot', '0002_alter_recommendinterest_plcyno'),
        ('Home', '0003_policies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Policy',
        ),
        migrations.DeleteModel(
            name='PolicyRaw',
        ),
        migrations.AddIndex(
            model_name='policies',
            index=models.Index(fields=['sprt_trgt_min_age', 'sprt_trgt_max_age'], name='idx_policies_age'),
        ),
        migrations.AddIndex(
            model_name='policies',
            index=models.Index(fields=['aply_bgng_ymd', 'aply_end_ymd'], name='idx_policies_aply_dates'),
        ),
        migrations.AddIndex(
            model_name='policies',
            index=models.Index(fields=['lclsf_nm', 'mclsf_nm'], name='idx_policies_classification'),
        ),
        migrations.AddIndex(
            model_name='policies',
            index=models.Index(fields=['plcy_nm'], name='idx_policies_plcy_nm'),
        ),
    ]
