# Generated by Django 5.2.1 on 2025-06-07 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_rename_user_id_refreshtoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='expired_dt',
            field=models.DateTimeField(verbose_name='만료일시'),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='token',
            field=models.TextField(unique=True, verbose_name='토큰'),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='token_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='토큰 아이디'),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자 아이디'),
        ),
        migrations.AlterField(
            model_name='user',
            name='addr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='인증 아이디'),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_server',
            field=models.CharField(max_length=50, verbose_name='인증 서버'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='생일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthyear',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='출생년도'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.URLField(blank=True, null=True, verbose_name='프로필 이미지'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='사용자 아이디'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_nm',
            field=models.CharField(max_length=100, verbose_name='이름'),
        ),
    ]
