# Generated by Django 5.2.1 on 2025-06-20 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_refreshtoken_create_dt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False, verbose_name='알림 상태 아이디')),
                ('last_checked_count', models.IntegerField(default=0, verbose_name='마지막 확인한 정책 개수')),
                ('last_checked_dt', models.DateTimeField(auto_now=True, verbose_name='마지막 확인 일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자 아이디')),
            ],
            options={
                'unique_together': {('user',)},
            },
        ),
    ]
