name: Deploy to AWS

on:
  push:
    branches:
      - develop

env:
  AWS_REGION: ap-northeast-2
  LAMBDA_FUNCTION_NAME: youth-policy-data-processor

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r aws_deploy/lambda_functions/data_processing/requirements.txt
        pip install awscli
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Create deployment package
      run: |
        cd aws_deploy/lambda_functions/data_processing
        zip -r ../../../deployment.zip .
        cd ../../..
        zip -g deployment.zip data/code/preprocessing.py data/code/insert_data_in_postgres.py
    
    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
          --zip-file fileb://deployment.zip 